blank_issues_enabled: false
contact_links:
  - name: 💬 Discussão geral
    url: https://github.com/RodrigoGalvao9/Editor-de-texto/discussions
    about: Use o Discussions para ideias soltas ou dúvidas gerais.
