name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

env:
  QT_QPA_PLATFORM: offscreen
  QT_LOGGING_RULES: "qt.*.debug=true"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests -v --showlocals --disable-warnings --tb=short

    - name: Save version tag to file
      run: echo "${GITHUB_REF#refs/tags/}" > App/version.txt
      

    - name: Build executable
      run: |
        pip install pyinstaller
        python -c "import spellchecker; import os; print(f'{os.path.dirname(spellchecker.__file__)}/resources/pt.json.gz:spellchecker/resources')" > resource_paths.txt
        pyinstaller --onefile --noconsole --name "BlocoDeNotas.exe" --add-data "$(cat resource_paths.txt)" main.py

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: BlocoDeNotas-executable-windows
        path: dist/BlocoDeNotas.exe
    
    
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1 libgl1-mesa-dev libxkbcommon-x11-0 libxcb-xinerama0
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests -v --showlocals --disable-warnings --tb=short

    - name: Save version tag to file
      run: echo "${GITHUB_REF#refs/tags/}" > App/version.txt
      
    - name: Build executable
      run: |
        pip install pyinstaller
        python -c "import spellchecker; import os; print(f'{os.path.dirname(spellchecker.__file__)}/resources/pt.json.gz:spellchecker/resources')" > resource_paths.txt
        pyinstaller --onefile --noconsole --name "BlocoDeNotas" --add-data "$(cat resource_paths.txt)" main.py

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
         name: BlocoDeNotas-executable-linux
         path: dist/BlocoDeNotas
    
  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: BlocoDeNotas-executable-windows
        path: artifacts/

    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: BlocoDeNotas-executable-linux
        path: artifacts/

    - name: Display downloaded files
      run: ls -R artifacts/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: |
          artifacts/BlocoDeNotas.exe
          artifacts/BlocoDeNotas
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        