name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  QT_QPA_PLATFORM: offscreen
  QT_LOGGING_RULES: "qt.*.debug=true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1 libxkbcommon-x11-0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests -v --showlocals --disable-warnings --tb=short

    - name: Build executable
      run: |
        pip install pyinstaller
        python -c "import spellchecker; import os; print(f'{os.path.dirname(spellchecker.__file__)}/resources/pt.json.gz:spellchecker/resources')" > resource_paths.txt
        pyinstaller --onefile --noconsole --name "BlocoDeNotas" --add-data "$(cat resource_paths.txt)" main.py

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: BlocoDeNotas-executable
        path: dist/BlocoDeNotas.exe