name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: bloco-de-notas
          environment-file: environment.yml
          python-version: 3.10

      - name: Install dependencies
        run: conda env update --file environment.yml --prune

      - name: Run tests
        run: |
          python -m unittest discover